on:
  # Trigger analysis when pushing in "main" branch. Change this to another branch if you need to
  push:
    branches:
      - main

name: Scanner Workflow
jobs:
  tmscan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TestMachine Scan
        uses: testmachine-ai/github-action@v0.1
        with:
          # All arguments are required
          # TM_REPOSITORY_ID: Use an already existing repository id (in this example: 120)
          # TM_SOURCE: The json file (or .zip with many .json files inside) with the compiled contract(s) you want to analyze (in this example: ourContracts.zip)
          TM_REPOSITORY_ID: 223
          TM_SOURCE: src/Coin.sol
        env:
          # All env variables are required
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TM_TOKEN_KEY: ${{ secrets.TM_TOKEN_KEY }}
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: result-report
          path: action_work_result_report.pdf